runtime: python39  # or python38 or any other supported version
entrypoint: python main.py
service: conversion
instance_class: F2


automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic
